In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\user\3mtt\env\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\users\user\3mtt\env\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\3mtt\env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\user\3mtt\env\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\user\3mtt\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
numberList = [1,2,3,4,5]

for number in numberList:
    print (number)

1
2
3
4
5

In [4]:
##Define a function that takes a list of sales amounts. Use a for loop with an if statement to print amounts over 100.

def purchases_100(salesAmounts):
    count = 0
    for salesAmount in salesAmounts:
        if salesAmount > 100:
            count += 1
    print (count)

purchases_100([50, 150, 200, 10])

2

In [5]:
amounts = [34, 180, 450, 120, 340]
salesAmounts = [salesAmount for salesAmount in amounts if salesAmount > 100 ]
salesAmounts

[180, 450, 120, 340]

In [6]:
count = sum(1 for salesAmount in amounts if salesAmount > 100)
count

4

# 3MTT task 8

In [7]:
df = pd.read_csv("77266340-2b93-406c-aac8-a8c635d7aed1.csv")

In [8]:
df.head()

   state_code  state_name  county_code county_name   aqi
0           6  California            1     Alameda  11.0
1           6  California            7       Butte   6.0
2           6  California           19      Fresno  11.0
3           6  California           29        Kern   7.0
4           6  California           29        Kern   3.0

In [9]:
# Apply a Boolean mask to filter the DataFrame for AQI levels greater than a specified threshold.


hazardous_df = df[df["aqi"] > 50].describe()
hazardous= df[df["aqi"] > 50]

In [10]:
hazardous_df

       state_code  county_code        aqi
count         2.0          2.0   2.000000
mean          6.0         37.0  76.000000
std           0.0          0.0  24.041631
min           6.0         37.0  59.000000
25%           6.0         37.0  67.500000
50%           6.0         37.0  76.000000
75%           6.0         37.0  84.500000
max           6.0         37.0  93.000000

In [11]:
hazardous

     state_code  state_name  county_code  county_name   aqi
76            6  California           37  Los Angeles  93.0
146           6  California           37  Los Angeles  59.0